name: light
description: Plugin for collecting data from the ambient light sensor on Android.
version: 3.0.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.light
        pluginClass: LightPlugin
      ios:
        pluginClass: LightPlugin
